#ifndef _PINS_H__
#define _PINS_H__

#define DEVICE_ACTIVE_PIN 13

#define MOTOR_KNEE_THROTTLE_PIN 12
#define MOTOR_KNEE_PRESSURE_IN A3
#define MOTOR_KNEE_LOAD_IN A4

#define MOTOR_HIP_THROTTLE_PIN 11
#define MOTOR_HIP_PRESSURE_IN A5
#define MOTOR_HIP_LOAD_IN A6

#define POT_BOX_P_PIN A0
#define POT_BOX_I_PIN A1
#define POT_BOX_D_PIN A2
#define POT_BOX_INTERRUPT_ID 0
#define POT_BOX_INTERRUPT_PIN 2

#define SETPOINT_PLUS_PIN 25
#define SETPOINT_MINUS_PIN 24

#endif //_PINS_H__
